# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/lib/CanonicalMoments"
      - "/lib/CanonicalMoments/docs"
      - "/lib/CanonicalMoments/examples"
      - "/lib/DiscreteMeasures"
      - "/lib/DiscreteMeasures/docs"
      - "/lib/OUQBase"
    schedule:
      interval: "daily"
    groups:
      all-julia-packages:
        patterns:
          - "*"
