name: CI
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        group:
          - Core
        version:
          - 'lts'
          - '1.11'
          - '1'
          - 'pre'
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - name: Develop local path deps (Julia < 1.11)
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          if VERSION < v"1.11.0-DEV.0"
            toml = Pkg.TOML.parsefile("Project.toml")
            if haskey(toml, "sources")
              specs = Pkg.PackageSpec[]
              for (dep, spec) in toml["sources"]
                if spec isa Dict && haskey(spec, "path") && isdir(spec["path"])
                  @info "Developing" dep spec["path"]
                  push!(specs, Pkg.PackageSpec(path=spec["path"]))
                end
              end
              isempty(specs) || Pkg.develop(specs)
            end
          end
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
          check_bounds: auto
        env:
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
          disable_safe_directory: true
